name: seg_nlp
channels:
- defaults
dependencies:
- seaborn==0.7.0
- pandas==0.20.3
- requests==2.13.0
- numpy==1.11.2
- nltk==3.2.4
- matplotlib==1.5.1
- ipython==4.2.0
- beautifulsoup4==4.6.0
- scikit-learn=0.18.1=np111py27_0  
- pip:
  - wordcloud==1.3.1